### ISSUE TITLE
多轮会话的外部知识设置

### ISSUE THREAD

**Issue by Qzsl123** [salesforce/DialogStudio#2]
论文中写道，We use the format Instruction \n <USER> user utterance <SYSTEM> system response <USER> ... <USER> user utterance \n <EXTERNAL KNOWLEDGE> supported knowledge to train the model
这里是每次只预测一轮response吗，这样每轮的EXTERNAL KNOWLEDGE是确定的；
如果同时预测多轮response，不同轮次的EXTERNAL KNOWLEDGE是不同的吧，这种情况该怎么处理呢

**Comment by qbetterk** [comment]
在外部知识固定的时候，我们每个turn都使用相同的EK（如MULTIWOZ2_2），此时为了标注方便我们在dialog-level给出EK的：dialog['external knowledge']；
而当EK随着对话的进行每轮都在变化的时候（如wizard_of_wikipedia），我们在每个turn都会标明相应的EK：dialog['log'][turn_id]['external knowledge']
